### ISSUE TITLE
"Next question" doesn't save the answer

### ISSUE THREAD

**Issue by TimothyLowYK** [LWK19/acmc2022#3]
Clicking on another question also doesn't save the answer

**Comment by LWK19** [comment]
It is not supposed to, to prevent submitting answers when the students are randomly clicking. If they choose an answer and didnt click save, they will assume that the answer is not saved,  so they may want to go back to that question

**Comment by TimothyLowYK** [comment]
I think "next question" should at least save the answer? people might forget to save between pages. But if not it's fine, just need to make it explicit to them. Maybe you can save only if the answer is different from the answer saved in the local array?
