### ISSUE TITLE
Some input sanitation required

### ISSUE THREAD

**Issue by TimothyLowYK** [LWK19/acmc2022#4]
<img width="924" alt="image" src="https://user-images.githubusercontent.com/30572072/166091575-bd2d5e16-e274-4b6b-9961-1da589fc048a.png">

This can be edited to "text", and any input can be inputted into the sheet. 

For example, "=indirect(address(row()-2,column()))" to extract the cell above 

same with this:
<img width="903" alt="image" src="https://user-images.githubusercontent.com/30572072/166092285-19f01429-bd64-4457-8c3d-b383cb0fe2c2.png">

**Comment by LWK19** [comment]
Not sure what  "=indirect(address(row()-2,column()))" means but I'm sure you cant get data from other columns that easily. Number sanitisation done.
